name: super_strapi_generated
description: A starting point for Dart libraries or applications.

dependencies:
  simple_strapi:
    path: /media/yadu/yadu/code/bigmints/bapp_/packages/simple_strapi

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

environment:
  sdk: "2.13.0-116.0.dev"

super_strapi:
  enabled: true

