name: super_strapi_generated
description: A new Flutter package project.
version: "0.0.1"
environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=2.0.2"
dependencies:
  flutter:
    sdk: flutter
  simple_strapi: 0.9.1-alpha+5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
super_strapi:
  enabled: true