name: bapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.18.0+1
  firebase_messaging: ^7.0.0
  firebase_storage: ^4.0.0
  firebase_crashlytics: ^0.2.0
  firebase_core: ^0.5.0
  provider: ^4.3.2+2
  flutter_mobx: ^1.1.0+2
  flutter_svg: ^0.19.0
  permission_handler: ^5.0.1+1
  device_info: ^0.4.2+8
  path_provider: ^1.6.18
  hive: ^1.4.4
  carousel_slider: ^2.2.1
  geolocator: ^6.0.0+4
  cloud_firestore: ^0.14.0+2
  feather_icons_flutter: ^4.7.4
  table_calendar: ^2.2.3
  enum_to_string: ^1.0.13
  pull_to_refresh: ^1.6.2
  bubble_tab_indicator: ^0.1.4
  flushbar: ^1.10.4
  intl_phone_number_input: any
  country_codes: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Gilmer
      fonts:
        - asset: assets/fonts/Gilmer/Gilmer-Bold.ttf
          weight: 900
        - asset: assets/fonts/Gilmer/Gilmer-Heavy.ttf
          weight: 800
        - asset: assets/fonts/Gilmer/Gilmer-Regular.ttf
          weight: 700
        - asset: assets/fonts/Gilmer/Gilmer-Medium.ttf
          weight: 700
        - asset: assets/fonts/Gilmer/Gilmer-Light.ttf
          weight: 100
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato/Lato-Heavy.ttf
          weight: 800
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Lato/Lato-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 200
