name: bapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.2.0+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #FIREBASE
  firebase_auth: ^0.18.4
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.2.0
  firebase_crashlytics: ^0.2.4
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  cloud_functions: ^0.7.2

  #STATE MANAGEMENT
  provider: ^4.3.2+2
  flutter_mobx: ^1.1.0+2
  event_bus: ^1.1.1

  #DEVICE
  permission_handler: ^5.0.1+1
  device_info: ^0.4.2+8
  path_provider: ^1.6.18
  hive: ^1.4.4
  multi_image_picker: ^4.7.14
  flutter_absolute_path: ^1.0.6
  screen: ^0.0.5
  notification_permissions: ^0.4.8

  #GIT
  the_country_number_widgets: 0.9.0
  the_country_number: 0.9.0

  #ICONS
  feather_icons_flutter: ^4.7.4
  cupertino_icons: ^0.1.3

  #MISC
  enum_to_string: ^1.0.13
  url_launcher: ^5.7.2
  intl: ^0.16.1
  uuid: ^2.2.2
  pdf: ^1.11.2
  image: ^2.1.19

  #UI
  animated_text_kit: ^2.2.0
  country_pickers: ^1.3.0
  pin_code_fields: ^5.2.0
  pull_to_refresh: ^1.6.2
  bubble_tab_indicator: ^0.1.4
  flushbar: ^1.10.4
  table_calendar: ^2.2.3
  carousel_slider: ^2.2.1
  flutter_svg: ^0.18.0
  cached_network_image: ^2.3.2+1
  expandable: ^4.1.4
  date_range_picker: ^1.0.6
  time_range_picker: ^1.1.0
  chips_choice: ^2.0.1
  flutter_svg_provider: ^0.1.6
  flutter_rating_bar: ^3.2.0
  flutter_week_view: any
  #forked update/should be changed to pub.dev when released
  textfield_tags:
    git:
      url: https://github.com/ondbyte/textfield_tags.git
  show_up_animation: ^1.0.2


  # MAPS
  google_maps_flutter: ^1.0.2
  google_place: ^0.3.3
  geocoder: ^0.2.1
  geolocator: ^6.0.0+4

   

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  test: ^1.15.5
  flutter_launcher_icons: ^0.8.1
  pedantic: ^1.0.0
  taste:
    git:
      url: https://github.com/ondbyte/taste.git

  


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/appIcons/ios.jpg"
  image_path_android: "assets/appIcons/android.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Gilmer
      fonts:
        - asset: assets/fonts/Gilmer/Gilmer-Bold.ttf
          weight: 900
        - asset: assets/fonts/Gilmer/Gilmer-Heavy.ttf
          weight: 800
        - asset: assets/fonts/Gilmer/Gilmer-Regular.ttf
          weight: 700
        - asset: assets/fonts/Gilmer/Gilmer-Medium.ttf
          weight: 700
        - asset: assets/fonts/Gilmer/Gilmer-Light.ttf
          weight: 100
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato/Lato-Heavy.ttf
          weight: 800
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Lato/Lato-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 200

