String data = '''[
  {
    "Name": "افغانستان",
    "DialCode": "+93",
    "Iso2": "AF",
    "EnglishName": "Afghanistan",
    "Iso3": "AFG",
    "Unicode": "",
    "Currency": "AFN",
    "Capital": "Kabul",
    "Continent": "AS",
    "DialLength": 9
  },
  {
    "Name": "Åland",
    "DialCode": "+358",
    "Iso2": "AX",
    "EnglishName": "Aland Islands",
    "Iso3": "ALA",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Mariehamn",
    "Continent": "EU",
    "DialLength": 10
  },
  {
    "Name": "Shqipëria",
    "DialCode": "+355",
    "Iso2": "AL",
    "EnglishName": "Albania",
    "Iso3": "ALB",
    "Unicode": "",
    "Currency": "ALL",
    "Capital": "Tirana",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "الجزائر",
    "DialCode": "+213",
    "Iso2": "DZ",
    "EnglishName": "Algeria",
    "Iso3": "DZA",
    "Unicode": "",
    "Currency": "DZD",
    "Capital": "Algiers",
    "Continent": "AF",
    "DialLength": 9
  },
  {
    "Name": "American Samoa",
    "DialCode": "+1684",
    "Iso2": "AS",
    "EnglishName": "American Samoa",
    "Iso3": "ASM",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "Pago Pago",
    "Continent": "OC",
    "DialLength": 10
  },
  {
    "Name": "Andorra",
    "DialCode": "+376",
    "Iso2": "AD",
    "EnglishName": "Andorra",
    "Iso3": "AND",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Andorra la Vella",
    "Continent": "EU",
    "DialLength": -1
  },
  {
    "Name": "Angola",
    "DialCode": "+244",
    "Iso2": "AO",
    "EnglishName": "Angola",
    "Iso3": "AGO",
    "Unicode": "",
    "Currency": "AOA",
    "Capital": "Luanda",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Anguilla",
    "DialCode": "+1264",
    "Iso2": "AI",
    "EnglishName": "Anguilla",
    "Iso3": "AIA",
    "Unicode": "",
    "Currency": "XCD",
    "Capital": "The Valley",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "Antarctica",
    "DialCode": "+672",
    "Iso2": "AQ",
    "EnglishName": "Antarctica",
    "Iso3": "ATA",
    "Unicode": "",
    "Currency": "",
    "Capital": "",
    "Continent": "AN",
    "DialLength": -1
  },
  {
    "Name": "Antigua and Barbuda",
    "DialCode": "+1268",
    "Iso2": "AG",
    "EnglishName": "Antigua and Barbuda",
    "Iso3": "ATG",
    "Unicode": "",
    "Currency": "XCD",
    "Capital": "St. John's",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "Argentina",
    "DialCode": "+54",
    "Iso2": "AR",
    "EnglishName": "Argentina",
    "Iso3": "ARG",
    "Unicode": "",
    "Currency": "ARS",
    "Capital": "Buenos Aires",
    "Continent": "SA",
    "DialLength": -1
  },
  {
    "Name": "Հայաստան",
    "DialCode": "+374",
    "Iso2": "AM",
    "EnglishName": "Armenia",
    "Iso3": "ARM",
    "Unicode": "",
    "Currency": "AMD",
    "Capital": "Yerevan",
    "Continent": "AS",
    "DialLength": 6
  },
  {
    "Name": "Aruba",
    "DialCode": "+297",
    "Iso2": "AW",
    "EnglishName": "Aruba",
    "Iso3": "ABW",
    "Unicode": "",
    "Currency": "AWG",
    "Capital": "Oranjestad",
    "Continent": "NA",
    "DialLength": 7
  },
  {
    "Name": "Australia",
    "DialCode": "+61",
    "Iso2": "AU",
    "EnglishName": "Australia",
    "Iso3": "AUS",
    "Unicode": "",
    "Currency": "AUD",
    "Capital": "Canberra",
    "Continent": "OC",
    "DialLength": 9
  },
  {
    "Name": "Österreich",
    "DialCode": "+43",
    "Iso2": "AT",
    "EnglishName": "Austria",
    "Iso3": "AUT",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Vienna",
    "Continent": "EU",
    "DialLength": [10,11]
  },
  {
    "Name": "Azərbaycan",
    "DialCode": "+994",
    "Iso2": "AZ",
    "EnglishName": "Azerbaijan",
    "Iso3": "AZE",
    "Unicode": "",
    "Currency": "AZN",
    "Capital": "Baku",
    "Continent": "AS",
    "DialLength": 9
  },
  {
    "Name": "Bahamas",
    "DialCode": "+1242",
    "Iso2": "BS",
    "EnglishName": "Bahamas",
    "Iso3": "BHS",
    "Unicode": "",
    "Currency": "BSD",
    "Capital": "Nassau",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "‏البحرين",
    "DialCode": "+973",
    "Iso2": "BH",
    "EnglishName": "Bahrain",
    "Iso3": "BHR",
    "Unicode": "",
    "Currency": "BHD",
    "Capital": "Manama",
    "Continent": "AS",
    "DialLength": 8
  },
  {
    "Name": "Bangladesh",
    "DialCode": "+880",
    "Iso2": "BD",
    "EnglishName": "Bangladesh",
    "Iso3": "BGD",
    "Unicode": "",
    "Currency": "BDT",
    "Capital": "Dhaka",
    "Continent": "",
    "DialLength": 10
  },
  {
    "Name": "Barbados",
    "DialCode": "+1246",
    "Iso2": "BB",
    "EnglishName": "Barbados",
    "Iso3": "BRB",
    "Unicode": "",
    "Currency": "BBD",
    "Capital": "Bridgetown",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "Белару́сь",
    "DialCode": "+375",
    "Iso2": "BY",
    "EnglishName": "Belarus",
    "Iso3": "BLR",
    "Unicode": "",
    "Currency": "BYR",
    "Capital": "Minsk",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "België",
    "DialCode": "+32",
    "Iso2": "BE",
    "EnglishName": "Belgium",
    "Iso3": "BEL",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Brussels",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "Belize",
    "DialCode": "+501",
    "Iso2": "BZ",
    "EnglishName": "Belize",
    "Iso3": "BLZ",
    "Unicode": "",
    "Currency": "BZD",
    "Capital": "Belmopan",
    "Continent": "NA",
    "DialLength": 7
  },
  {
    "Name": "Bénin",
    "DialCode": "+229",
    "Iso2": "BJ",
    "EnglishName": "Benin",
    "Iso3": "BEN",
    "Unicode": "",
    "Currency": "XOF",
    "Capital": "Porto-Novo",
    "Continent": "AF",
    "DialLength": [6,7,8,9]
  },
  {
    "Name": "Bermuda",
    "DialCode": "+1441",
    "Iso2": "BM",
    "EnglishName": "Bermuda",
    "Iso3": "BMU",
    "Unicode": "",
    "Currency": "BMD",
    "Capital": "Hamilton",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "ʼbrug-yul",
    "DialCode": "+975",
    "Iso2": "BT",
    "EnglishName": "Bhutan",
    "Iso3": "BTN",
    "Unicode": "",
    "Currency": "BTN",
    "Capital": "Thimphu",
    "Continent": "AS",
    "DialLength": -1
  },
  {
    "Name": "Bolivia",
    "DialCode": "+591",
    "Iso2": "BO",
    "EnglishName": "Bolivia",
    "Iso3": "BOL",
    "Unicode": "",
    "Currency": "BOB",
    "Capital": "Sucre",
    "Continent": "SA",
    "DialLength": -1
  },
  {
    "Name": "Bosna i Hercegovina",
    "DialCode": "+387",
    "Iso2": "BA",
    "EnglishName": "Bosnia and Herzegovina",
    "Iso3": "BIH",
    "Unicode": "",
    "Currency": "BAM",
    "Capital": "Sarajevo",
    "Continent": "EU",
    "DialLength": 8
  },
  {
    "Name": "Botswana",
    "DialCode": "+267",
    "Iso2": "BW",
    "EnglishName": "Botswana",
    "Iso3": "BWA",
    "Unicode": "",
    "Currency": "BWP",
    "Capital": "Gaborone",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Bouvetøya",
    "DialCode": "+47",
    "Iso2": "BV",
    "EnglishName": "Bouvet Island",
    "Iso3": "BVT",
    "Unicode": "",
    "Currency": "NOK",
    "Capital": "",
    "Continent": "AN",
    "DialLength": -1

  },
  {
    "Name": "Brasil",
    "DialCode": "+55",
    "Iso2": "BR",
    "EnglishName": "Brazil",
    "Iso3": "BRA",
    "Unicode": "",
    "Currency": "BRL",
    "Capital": "Brasilia",
    "Continent": "SA",
    "DialLength": 11
  },
  {
    "Name": "British Indian Ocean Territory",
    "DialCode": "+246",
    "Iso2": "IO",
    "EnglishName": "British Indian Ocean Territory",
    "Iso3": "IOT",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "Diego Garcia",
    "Continent": "AS",
    "DialLength":[]
  },
  {
    "Name": "Negara Brunei Darussalam",
    "DialCode": "+673",
    "Iso2": "BN",
    "EnglishName": "Brunei",
    "Iso3": "BRN",
    "Unicode": "",
    "Currency": "BND",
    "Capital": "Bandar Seri Begawan",
    "Continent": "AS",
    "DialLength": -1
  },
  {
    "Name": "България",
    "DialCode": "+359",
    "Iso2": "BG",
    "EnglishName": "Bulgaria",
    "Iso3": "BGR",
    "Unicode": "",
    "Currency": "BGN",
    "Capital": "Sofia",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "Burkina Faso",
    "DialCode": "+226",
    "Iso2": "BF",
    "EnglishName": "Burkina Faso",
    "Iso3": "BFA",
    "Unicode": "",
    "Currency": "XOF",
    "Capital": "Ouagadougou",
    "Continent": "AF",
    "DialLength": 8
  },
  {
    "Name": "Burundi",
    "DialCode": "+257",
    "Iso2": "BI",
    "EnglishName": "Burundi",
    "Iso3": "BDI",
    "Unicode": "",
    "Currency": "BIF",
    "Capital": "Bujumbura",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Cambodia",
    "DialCode": "+855",
    "Iso2": "KH",
    "EnglishName": "Cambodia",
    "Iso3": "KHM",
    "Unicode": "",
    "Currency": "KHR",
    "Capital": "Phnom Penh",
    "Continent": "AS",
    "DialLength": 9
  },
  {
    "Name": "Cameroon",
    "DialCode": "+237",
    "Iso2": "CM",
    "EnglishName": "Cameroon",
    "Iso3": "CMR",
    "Unicode": "",
    "Currency": "XAF",
    "Capital": "Yaounde",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Canada",
    "DialCode": "+1",
    "Iso2": "CA",
    "EnglishName": "Canada",
    "Iso3": "CAN",
    "Unicode": "",
    "Currency": "CAD",
    "Capital": "Ottawa",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "Cabo Verde",
    "DialCode": "+238",
    "Iso2": "CV",
    "EnglishName": "Cape Verde",
    "Iso3": "CPV",
    "Unicode": "",
    "Currency": "CVE",
    "Capital": "Praia",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Cayman Islands",
    "DialCode": "+1345",
    "Iso2": "KY",
    "EnglishName": "Cayman Islands",
    "Iso3": "CYM",
    "Unicode": "",
    "Currency": "KYD",
    "Capital": "George Town",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "Ködörösêse tî Bêafrîka",
    "DialCode": "+236",
    "Iso2": "CF",
    "EnglishName": "Central African Republic",
    "Iso3": "CAF",
    "Unicode": "",
    "Currency": "XAF",
    "Capital": "Bangui",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Tchad",
    "DialCode": "+235",
    "Iso2": "TD",
    "EnglishName": "Chad",
    "Iso3": "TCD",
    "Unicode": "",
    "Currency": "XAF",
    "Capital": "N'Djamena",
    "Continent": "AF",
    "DialLength": 8

  },
  {
    "Name": "Chile",
    "DialCode": "+56",
    "Iso2": "CL",
    "EnglishName": "Chile",
    "Iso3": "CHL",
    "Unicode": "",
    "Currency": "CLP",
    "Capital": "Santiago",
    "Continent": "SA",
    "DialLength": 9
  },
  {
    "Name": "中国",
    "DialCode": "+86",
    "Iso2": "CN",
    "EnglishName": "China",
    "Iso3": "CHN",
    "Unicode": "",
    "Currency": "CNY",
    "Capital": "Beijing",
    "Continent": "AS",
    "DialLength": [11,13,11]

  },
  {
    "Name": "Christmas Island",
    "DialCode": "+61",
    "Iso2": "CX",
    "EnglishName": "Christmas Island",
    "Iso3": "CXR",
    "Unicode": "",
    "Currency": "AUD",
    "Capital": "Flying Fish Cove",
    "Continent": "AS",
    "DialLength": -1
  },
  {
    "Name": "Cocos (Keeling) Islands",
    "DialCode": "+61",
    "Iso2": "CC",
    "EnglishName": "Cocos Islands",
    "Iso3": "CCK",
    "Unicode": "",
    "Currency": "AUD",
    "Capital": "West Island",
    "Continent": "AS",
    "DialLength": -1
  },
  {
    "Name": "Colombia",
    "DialCode": "+57",
    "Iso2": "CO",
    "EnglishName": "Colombia",
    "Iso3": "COL",
    "Unicode": "",
    "Currency": "COP",
    "Capital": "Bogota",
    "Continent": "SA",
    "DialLength": 10
  },
  {
    "Name": "Komori",
    "DialCode": "+269",
    "Iso2": "KM",
    "EnglishName": "Comoros",
    "Iso3": "COM",
    "Unicode": "",
    "Currency": "KMF",
    "Capital": "Moroni",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "République du Congo",
    "DialCode": "+242",
    "Iso2": "CG",
    "EnglishName": "Republic of the Congo",
    "Iso3": "COG",
    "Unicode": "",
    "Currency": "XAF",
    "Capital": "Brazzaville",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "République démocratique du Congo",
    "DialCode": "+243",
    "Iso2": "CD",
    "EnglishName": "Democratic Republic of the Congo",
    "Iso3": "COD",
    "Unicode": "",
    "Currency": "CDF",
    "Capital": "Kinshasa",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Cook Islands",
    "DialCode": "+682",
    "Iso2": "CK",
    "EnglishName": "Cook Islands",
    "Iso3": "COK",
    "Unicode": "",
    "Currency": "NZD",
    "Capital": "Avarua",
    "Continent": "OC",
    "DialLength": 5
  },
  {
    "Name": "Costa Rica",
    "DialCode": "+506",
    "Iso2": "CR",
    "EnglishName": "Costa Rica",
    "Iso3": "CRI",
    "Unicode": "",
    "Currency": "CRC",
    "Capital": "San Jose",
    "Continent": "NA",
    "DialLength": 8
  },
  {
    "Name": "Côte d'Ivoire",
    "DialCode": "+225",
    "Iso2": "CI",
    "EnglishName": "Ivory Coast",
    "Iso3": "CIV",
    "Unicode": "",
    "Currency": "XOF",
    "Capital": "Yamoussoukro",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Hrvatska",
    "DialCode": "+385",
    "Iso2": "HR",
    "EnglishName": "Croatia",
    "Iso3": "HRV",
    "Unicode": "",
    "Currency": "HRK",
    "Capital": "Zagreb",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "Cuba",
    "DialCode": "+53",
    "Iso2": "CU",
    "EnglishName": "Cuba",
    "Iso3": "CUB",
    "Unicode": "",
    "Currency": "CUP",
    "Capital": "Havana",
    "Continent": "NA",
    "DialLength": -1
  },
  {
    "Name": "Κύπρος",
    "DialCode": "+357",
    "Iso2": "CY",
    "EnglishName": "Cyprus",
    "Iso3": "CYP",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Nicosia",
    "Continent": "EU",
    "DialLength": 8
  },
  {
    "Name": "Česká republika",
    "DialCode": "+420",
    "Iso2": "CZ",
    "EnglishName": "Czech Republic",
    "Iso3": "CZE",
    "Unicode": "",
    "Currency": "CZK",
    "Capital": "Prague",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "Danmark",
    "Dialcode": "+45",
    "Iso2": "DK",
    "EnglishName": "Denmark",
    "Iso3": "DNK",
    "Unicode": "",
    "Currency": "DKK",
    "Capital": "Copenhagen",
    "Continent": "EU",
    "DialLength": 8
  },
  {
    "Name": "Djibouti",
    "DialCode": "+253",
    "Iso2": "DJ",
    "EnglishName": "Djibouti",
    "Iso3": "DJI",
    "Unicode": "",
    "Currency": "DJF",
    "Capital": "Djibouti",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Dominica",
    "DialCode": "+1767",
    "Iso2": "DM",
    "EnglishName": "Dominica",
    "Iso3": "DMA",
    "Unicode": "",
    "Currency": "XCD",
    "Capital": "Roseau",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "República Dominicana",
    "DialCode": "+1",
    "Iso2": "DO",
    "EnglishName": "Dominican Republic",
    "Iso3": "DOM",
    "Unicode": "",
    "Currency": "DOP",
    "Capital": "Santo Domingo",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "Ecuador",
    "DialCode": "+593",
    "Iso2": "EC",
    "EnglishName": "Ecuador",
    "Iso3": "ECU",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "Quito",
    "Continent": "SA",
    "DialLength": [-1,9]
  },
  {
    "Name": "مصر‎",
    "DialCode": "+20",
    "Iso2": "EG",
    "EnglishName": "Egypt",
    "Iso3": "EGY",
    "Unicode": "",
    "Currency": "EGP",
    "Capital": "Cairo",
    "Continent": "AF",
    "DialLength": 10

  },
  {
    "Name": "El Salvador",
    "DialCode": "+503",
    "Iso2": "SV",
    "EnglishName": "El Salvador",
    "Iso3": "SLV",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "San Salvador",
    "Continent": "NA",
    "DialLength": 8

  },
  {
    "Name": "Guinea Ecuatorial",
    "DialCode": "+240",
    "Iso2": "GQ",
    "EnglishName": "Equatorial Guinea",
    "Iso3": "GNQ",
    "Unicode": "",
    "Currency": "XAF",
    "Capital": "Malabo",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "ኤርትራ",
    "DialCode": "+291",
    "Iso2": "ER",
    "EnglishName": "Eritrea",
    "Iso3": "ERI",
    "Unicode": "",
    "Currency": "ERN",
    "Capital": "Asmara",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Eesti",
    "DialCode": "+372",
    "Iso2": "EE",
    "EnglishName": "Estonia",
    "Iso3": "EST",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Tallinn",
    "Continent": "EU",
    "DialLength": -1
  },
  {
    "Name": "ኢትዮጵያ",
    "DialCode": "+251",
    "Iso2": "ET",
    "EnglishName": "Ethiopia",
    "Iso3": "ETH",
    "Unicode": "",
    "Currency": "ETB",
    "Capital": "Addis Ababa",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Falkland Islands",
    "DialCode": "+500",
    "Iso2": "FK",
    "EnglishName": "Falkland Islands",
    "Iso3": "FLK",
    "Unicode": "",
    "Currency": "FKP",
    "Capital": "Stanley",
    "Continent": "SA",
    "DialLength": 5
  },
  {
    "Name": "Føroyar",
    "DialCode": "+298",
    "Iso2": "FO",
    "EnglishName": "Faroe Islands",
    "Iso3": "FRO",
    "Unicode": "",
    "Dial": "298",
    "Currency": "DKK",
    "Capital": "Torshavn",
    "Continent": "EU",
    "DialLength": 5
  },
  {
    "Name": "Fiji",
    "DialCode": "+679",
    "Iso2": "FJ",
    "EnglishName": "Fiji",
    "Iso3": "FJI",
    "Unicode": "",
    "Currency": "FJD",
    "Capital": "Suva",
    "Continent": "OC",
    "DialLength": -1
  },
  {
    "Name": "Suomi",
    "DialCode": "+358",
    "Iso2": "FI",
    "EnglishName": "Finland",
    "Iso3": "FIN",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Helsinki",
    "Continent": "EU",
    "DialLength": [-1,10]
  },
  {
    "Name": "France",
    "DialCode": "+33",
    "Iso2": "FR",
    "EnglishName": "France",
    "Iso3": "FRA",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Paris",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "Guyane française",
    "DialCode": "+594",
    "Iso2": "GF",
    "EnglishName": "French Guiana",
    "Iso3": "GUF",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Cayenne",
    "Continent": "SA",
    "DialLength": [9,-1,12]
  },
  {
    "Name": "Polynésie française",
    "DialCode": "+689",
    "Iso2": "PF",
    "EnglishName": "French Polynesia",
    "Iso3": "PYF",
    "Unicode": "",
    "Currency": "XPF",
    "Capital": "Papeete",
    "Continent": "OC",
    "DialLength": 6
  },  
  {
    "Name": "Gabon",
    "DialCode": "+241",
    "Iso2": "GA",
    "EnglishName": "Gabon",
    "Iso3": "GAB",
    "Unicode": "",
    "Currency": "XAF",
    "Capital": "Libreville",
    "Continent": "AF",
    "DialLength": 7
  },
  {
    "Name": "Gambia",
    "DialCode": "+220",
    "Iso2": "GM",
    "EnglishName": "Gambia",
    "Iso3": "GMB",
    "Unicode": "",
    "Currency": "GMD",
    "Capital": "Banjul",
    "Continent": "AF",
    "DialLength": -1

  },
  {
    "Name": "საქართველო",
    "DialCode": "+995",
    "Iso2": "GE",
    "EnglishName": "Georgia",
    "Iso3": "GEO",
    "Unicode": "",
    "Currency": "GEL",
    "Capital": "Tbilisi",
    "Continent": "AS",
    "DialLength": 9
  },
  {
    "Name": "Deutschland",
    "DialCode": "+49",
    "Iso2": "DE",
    "EnglishName": "Germany",
    "Iso3": "DEU",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Berlin",
    "Continent": "EU",
    "DialLength": [10,11]
  },
  {
    "Name": "Ghana",
    "DialCode": "+233",
    "Iso2": "GH",
    "EnglishName": "Ghana",
    "Iso3": "GHA",
    "Unicode": "",
    "Currency": "GHS",
    "Capital": "Accra",
    "Continent": "AF",
    "DialLength": 9
  },
  {
    "Name": "Gibraltar",
    "DialCode": "+350",
    "Iso2": "GI",
    "EnglishName": "Gibraltar",
    "Iso3": "GIB",
    "Unicode": "",
    "Currency": "GIP",
    "Capital": "Gibraltar",
    "Continent": "EU",
    "DialLength": -1
  },
  {
    "Name": "Ελλάδα",
    "DialCode": "+30",
    "Iso2": "GR",
    "EnglishName": "Greece",
    "Iso3": "GRC",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Athens",
    "Continent": "EU",
    "DialLength": 10
  },
  {
    "Name": "Kalaallit Nunaat",
    "DialCode": "+299",
    "Iso2": "GL",
    "EnglishName": "Greenland",
    "Iso3": "GRL",
    "Unicode": "",
    "Currency": "DKK",
    "Capital": "Nuuk",
    "Continent": "NA",
    "DialLength": 6
  },
  {
    "Name": "Grenada",
    "DialCode": "+1473",
    "Iso2": "GD",
    "EnglishName": "Grenada",
    "Iso3": "GRD",
    "Unicode": "",
    "Currency": "XCD",
    "Capital": "St. George's",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "Guadeloupe",
    "DialCode": "+590",
    "Iso2": "GP",
    "EnglishName": "Guadeloupe",
    "Iso3": "GLP",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Basse-Terre",
    "Continent": "NA",
    "DialLength": [9,-1,12]
  },
  {
    "Name": "Guam",
    "DialCode": "+1671",
    "Iso2": "GU",
    "EnglishName": "Guam",
    "Iso3": "GUM",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "Hagatna",
    "Continent": "OC",
    "DialLength": 10
  },
  {
    "Name": "Guatemala",
    "DialCode": "+502",
    "Iso2": "GT",
    "EnglishName": "Guatemala",
    "Iso3": "GTM",
    "Unicode": "",
    "Currency": "GTQ",
    "Capital": "Guatemala City",
    "Continent": "NA",
    "DialLength": 8
  },
  {
    "Name": "Guernsey",
    "DialCode": "+44",
    "Iso2": "GG",
    "EnglishName": "Guernsey",
    "Iso3": "GGY",
    "Unicode": "",
    "Currency": "GBP",
    "Capital": "St Peter Port",
    "Continent": "EU",
    "DialLength": 10
  },
  {
    "Name": "Guinée",
    "DialCode": "+224",
    "Iso2": "GN",
    "EnglishName": "Guinea",
    "Iso3": "GIN",
    "Unicode": "",
    "Currency": "GNF",
    "Capital": "Conakry",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Guiné-Bissau",
    "DialCode": "+245",
    "Iso2": "GW",
    "EnglishName": "Guinea-Bissau",
    "Iso3": "GNB",
    "Unicode": "",
    "Currency": "XOF",
    "Capital": "Bissau",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Guyana",
    "DialCode": "+592",
    "Iso2": "GY",
    "EnglishName": "Guyana",
    "Iso3": "GUY",
    "Unicode": "",
    "Currency": "GYD",
    "Capital": "Georgetown",
    "Continent": "SA",
    "DialLength": -1
  },
  {
    "Name": "Haïti",
    "DialCode": "+509",
    "Iso2": "HT",
    "EnglishName": "Haiti",
    "Iso3": "HTI",
    "Unicode": "",
    "Currency": "HTG",
    "Capital": "Port-au-Prince",
    "Continent": "NA",
    "DialLength": -1
  },
  {
    "Name": "Heard Island and McDonald Islands",
    "DialCode": "+0",
    "Iso2": "HM",
    "EnglishName": "Heard Island and McDonald Islands",
    "Iso3": "HMD",
    "Unicode": "",
    "Currency": "AUD",
    "Capital": "",
    "Continent": "AN",
    "DialLength":[]
  },
  {
    "Name": "Vaticano",
    "DialCode": "+379",
    "Iso2": "VA",
    "EnglishName": "Vatican",
    "Iso3": "VAT",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Vatican City",
    "Continent": "EU",
    "DialLength": 10
  },
  {
    "Name": "Honduras",
    "DialCode": "+504",
    "Iso2": "HN",
    "EnglishName": "Honduras",
    "Iso3": "HND",
    "Unicode": "",
    "Currency": "HNL",
    "Capital": "Tegucigalpa",
    "Continent": "NA",
    "DialLength": 8
  },
  {
    "Name": "香港",
    "DialCode": "+852",
    "Iso2": "HK",
    "EnglishName": "Hong Kong",
    "Iso3": "HKG",
    "Unicode": "",
    "Currency": "HKD",
    "Capital": "Hong Kong",
    "Continent": "AS",
    "DialLength": 8
  },
  {
    "Name": "Magyarország",
    "DialCode": "+36",
    "Iso2": "HU",
    "EnglishName": "Hungary",
    "Iso3": "HUN",
    "Unicode": "",
    "Currency": "HUF",
    "Capital": "Budapest",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "Ísland",
    "DialCode": "+354",
    "Iso2": "IS",
    "EnglishName": "Iceland",
    "Iso3": "ISL",
    "Unicode": "",
    "Currency": "ISK",
    "Capital": "Reykjavik",
    "Continent": "EU",
    "DialLength": -1
  },
  {
    "Name": "भारत",
    "DialCode": "+91",
    "Iso2": "IN",
    "EnglishName": "India",
    "Iso3": "IND",
    "Unicode": "",
    "Currency": "INR",
    "Capital": "New Delhi",
    "Continent": "AS",
    "DialLength": 10
  },
  {
    "Name": "Indonesia",
    "DialCode": "+62",
    "Iso2": "ID",
    "EnglishName": "Indonesia",
    "Iso3": "IDN",
    "Unicode": "",
    "Currency": "IDR",
    "Capital": "Jakarta",
    "Continent": "AS",
    "DialLength": [9,10,11]
  },
  {
    "Name": "ایران",
    "DialCode": "+98",
    "Iso2": "IR",
    "EnglishName": "Iran",
    "Iso3": "IRN",
    "Unicode": "",
    "Currency": "IRR",
    "Capital": "Tehran",
    "Continent": "AS",
    "DialLength": [10,-1]
  },
  {
    "Name": "العراق",
    "DialCode": "+964",
    "Iso2": "IQ",
    "EnglishName": "Iraq",
    "Iso3": "IRQ",
    "Unicode": "",
    "Currency": "IQD",
    "Capital": "Baghdad",
    "Continent": "AS",
    "DialLength": -1
  },
  {
    "Name": "Éire",
    "DialCode": "+353",
    "Iso2": "IE",
    "EnglishName": "Ireland",
    "Iso3": "IRL",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Dublin",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "Isle of Man",
    "DialCode": "+44",
    "Iso2": "IM",
    "EnglishName": "Isle of Man",
    "Iso3": "IMN",
    "Unicode": "",
    "Currency": "GBP",
    "Capital": "Douglas, Isle of Man",
    "Continent": "EU",
    "DialLength": 10
  },
  {
    "Name": "ישראל",
    "DialCode": "+972",
    "Iso2": "IL",
    "EnglishName": "Israel",
    "Iso3": "ISR",
    "Unicode": "",
    "Currency": "ILS",
    "Capital": "Jerusalem",
    "Continent": "AS",
    "DialLength": 9
  },
  {
    "Name": "Italia",
    "DialCode": "+39",
    "Iso2": "IT",
    "EnglishName": "Italy",
    "Iso3": "ITA",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Rome",
    "Continent": "EU",
    "DialLength": [9,10,12,13]
  },
  {
    "Name": "Jamaica",
    "DialCode": "+1876",
    "Iso2": "JM",
    "EnglishName": "Jamaica",
    "Iso3": "JAM",
    "Unicode": "",
    "Currency": "JMD",
    "Capital": "Kingston",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "日本",
    "DialCode": "+81",
    "Iso2": "JP",
    "EnglishName": "Japan",
    "Iso3": "JPN",
    "Unicode": "",
    "Currency": "JPY",
    "Capital": "Tokyo",
    "Continent": "AS",
    "DialLength": 11
  },
  {
    "Name": "Jersey",
    "DialCode": "+44",
    "Iso2": "JE",
    "EnglishName": "Jersey",
    "Iso3": "JEY",
    "Unicode": "",
    "Currency": "GBP",
    "Capital": "Saint Helier",
    "Continent": "EU",
    "DialLength": 10
  },
  {
    "Name": "الأردن",
    "DialCode": "+962",
    "Iso2": "JO",
    "EnglishName": "Jordan",
    "Iso3": "JOR",
    "Unicode": "",
    "Currency": "JOD",
    "Capital": "Amman",
    "Continent": "AS",
    "DialLength": -1
  },
  {
    "Name": "Қазақстан",
    "DialCode": "+7",
    "Iso2": "KZ",
    "EnglishName": "Kazakhstan",
    "Iso3": "KAZ",
    "Unicode": "",
    "Currency": "KZT",
    "Capital": "Astana",
    "Continent": "AS",
    "DialLength": 10
  },
  {
    "Name": "Kenya",
    "DialCode": "+254",
    "Iso2": "KE",
    "EnglishName": "Kenya",
    "Iso3": "KEN",
    "Unicode": "",
    "Currency": "KES",
    "Capital": "Nairobi",
    "Continent": "AF",
    "DialLength": 10
  },
  {
    "Name": "Kiribati",
    "DialCode": "+686",
    "Iso2": "KI",
    "EnglishName": "Kiribati",
    "Iso3": "KIR",
    "Unicode": "",
    "Currency": "AUD",
    "Capital": "Tarawa",
    "Continent": "OC",
    "DialLength": 8
  },
  {
    "Name": "북한",
    "DialCode": "+850",
    "Iso2": "KP",
    "EnglishName": "North Korea",
    "Iso3": "PRK",
    "Unicode": "",
    "Currency": "KPW",
    "Capital": "Pyongyang",
    "Continent": "AS",
    "DialLength": -1
  },
  {
    "Name": "대한민국",
    "DialCode": "+82",
    "Iso2": "KR",
    "EnglishName": "South Korea",
    "Iso3": "KOR",
    "Unicode": "",
    "Currency": "KRW",
    "Capital": "Seoul",
    "Continent": "AS",
    "DialLength": -1
  },
  {
    "Name": "Republika e Kosovës",
    "DalCode": "+383",
    "Iso2": "XK",
    "EnglishName": "Kosovo",
    "Iso3": "XKX",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Pristina",
    "Continent": "EU",
    "DialLength": 8
  },
  {
    "Name": "الكويت",
    "DialCode": "+965",
    "Iso2": "KW",
    "EnglishName": "Kuwait",
    "Iso3": "KWT",
    "Unicode": "",
    "Currency": "KWD",
    "Capital": "Kuwait City",
    "Continent": "AS",
    "DialLength": 8
  },
  {
    "Name": "Кыргызстан",
    "DialCode": "+996",
    "Iso2": "KG",
    "EnglishName": "Kyrgyzstan",
    "Iso3": "KGZ",
    "Unicode": "",
    "Currency": "KGS",
    "Capital": "Bishkek",
    "Continent": "AS",
    "DialLength": -1
  },
  {
    "Name": "ສປປລາວ",
    "DialCode": "+856",
    "Iso2": "LA",
    "EnglishName": "Laos",
    "Iso3": "LAO",
    "Unicode": "",
    "Currency": "LAK",
    "Capital": "Vientiane",
    "Continent": "AS",
    "DialLength": -1
  },
  {
    "Name": "Latvija",
    "DialCode": "+371",
    "Iso2": "LV",
    "EnglishName": "Latvia",
    "Iso3": "LVA",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Riga",
    "Continent": "EU",
    "DialLength": 8
  },
  {
    "Name": "لبنان",
    "DialCode": "+961",
    "Iso2": "LB",
    "EnglishName": "Lebanon",
    "Iso3": "LBN",
    "Unicode": "",
    "Currency": "LBP",
    "Capital": "Beirut",
    "Continent": "AS",
    "DialLength": [-1,7,8]
  },
  {
    "Name": "Lesotho",
    "DialCode": "+266",
    "Iso2": "LS",
    "EnglishName": "Lesotho",
    "Iso3": "LSO",
    "Unicode": "",
    "Dial": "266",
    "Currency": "LSL",
    "Capital": "Maseru",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Liberia",
    "DialCode": "+231",
    "Iso2": "LR",
    "EnglishName": "Liberia",
    "Iso3": "LBR",
    "Unicode": "",
    "Currency": "LRD",
    "Capital": "Monrovia",
    "Continent": "AF",
    "DialLength": [7,8]
  },
  {
    "Name": "‏ليبيا",
    "DialCode": "+218",
    "Iso2": "LY",
    "EnglishName": "Libya",
    "Iso3": "LBY",
    "Unicode": "",
    "Currency": "LYD",
    "Capital": "Tripolis",
    "Continent": "AF",
    "DialLength": 10
  },
  {
    "Name": "Liechtenstein",
    "DialCode": "+423",
    "Iso2": "LI",
    "EnglishName": "Liechtenstein",
    "Iso3": "LIE",
    "Unicode": "",
    "Currency": "CHF",
    "Capital": "Vaduz",
    "Continent": "EU",
    "DialLength": -1
  },
  {
    "Name": "Lietuva",
    "DialCode": "+370",
    "Iso2": "LT",
    "EnglishName": "Lithuania",
    "Iso3": "LTU",
    "Unicode": "",
    "Currency": "LTL",
    "Capital": "Vilnius",
    "Continent": "EU",
    "DialLength": 8
  },
  {
    "Name": "Luxembourg",
    "DialCode": "+352",
    "Iso2": "LU",
    "EnglishName": "Luxembourg",
    "Iso3": "LUX",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Luxembourg",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "澳門",
    "DialCode": "+853",
    "Iso2": "MO",
    "EnglishName": "Macao",
    "Iso3": "MAC",
    "Unicode": "",
    "Currency": "MOP",
    "Capital": "Macao",
    "Continent": "AS",
    "DialLength": -1
  },
  {
    "Name": "Македонија",
    "DialDode": "+389",
    "Iso2": "MK",
    "EnglishName": "Macedonia",
    "Iso3": "MKD",
    "Unicode": "",
    "Currency": "MKD",
    "Capital": "Skopje",
    "Continent": "EU",
    "DialLength": 8
  },
  {
    "Name": "Madagasikara",
    "DialCode": "+261",
    "Iso2": "MG",
    "EnglishName": "Madagascar",
    "Iso3": "MDG",
    "Unicode": "",
    "Currency": "MGA",
    "Capital": "Antananarivo",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Malawi",
    "DialCode": "+265",
    "Iso2": "MW",
    "EnglishName": "Malawi",
    "Iso3": "MWI",
    "Unicode": "",
    "Currency": "MWK",
    "Capital": "Lilongwe",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Malaysia",
    "DialCode": "+60",
    "Iso2": "MY",
    "EnglishName": "Malaysia",
    "Iso3": "MYS",
    "Unicode": "",
    "Currency": "MYR",
    "Capital": "Kuala Lumpur",
    "Continent": "AS",
    "DialLength": [-1,7]
  },
  {
    "Name": "Maldives",
    "DialCode": "+960",
    "Iso2": "MV",
    "EnglishName": "Maldives",
    "Iso3": "MDV",
    "Unicode": "",
    "Currency": "MVR",
    "Capital": "Male",
    "Continent": "AS",
    "DialLength": 7
  },
  {
    "Name": "Mali",
    "DialCode": "+223",
    "Iso2": "ML",
    "EnglishName": "Mali",
    "Iso3": "MLI",
    "Unicode": "",
    "Currency": "XOF",
    "Capital": "Bamako",
    "Continent": "AF",
    "DialLength": [-1,8]
  },
  {
    "Name": "Malta",
    "DialCode": "+356",
    "Iso2": "MT",
    "EnglishName": "Malta",
    "Iso3": "MLT",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Valletta",
    "Continent": "EU",
    "DialLength": -1
  },
  {
    "Name": "M̧ajeļ",
    "DialCode": "+692",
    "Iso2": "MH",
    "EnglishName": "Marshall Islands",
    "Iso3": "MHL",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "Majuro",
    "Continent": "OC",
    "DialLength": 7
  },
  {
    "Name": "Martinique",
    "DialCode": "+596",
    "Iso2": "MQ",
    "EnglishName": "Martinique",
    "Iso3": "MTQ",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Fort-de-France",
    "Continent": "NA",
    "DialLength": [-1,9,12]
  },
  {
    "Name": "موريتانيا",
    "DialCode": "+222",
    "Iso2": "MR",
    "EnglishName": "Mauritania",
    "Iso3": "MRT",
    "Unicode": "",
    "Currency": "MRO",
    "Capital": "Nouakchott",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Maurice",
    "DialCode": "+230",
    "Iso2": "MU",
    "EnglishName": "Mauritius",
    "Iso3": "MUS",
    "Unicode": "",
    "Currency": "MUR",
    "Capital": "Port Louis",
    "Continent": "AF",
    "DialLength": 8
  },
  {
    "Name": "Mayotte",
    "DialCode": "+262",
    "Iso2": "YT",
    "EnglishName": "Mayotte",
    "Iso3": "MYT",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Mamoudzou",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "México",
    "DialCode": "+52",
    "Iso2": "MX",
    "EnglishName": "Mexico",
    "Iso3": "MEX",
    "Unicode": "",
    "Currency": "MXN",
    "Capital": "Mexico City",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "Micronesia",
    "DialCode": "+691",
    "Iso2": "FM",
    "EnglishName": "Micronesia",
    "Iso3": "FSM",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "Palikir",
    "Continent": "OC",
    "DialLength": 7
  },
  {
    "Name": "Moldova",
    "DialCode": "+373",
    "Iso2": "MD",
    "EnglishName": "Moldova",
    "Iso3": "MDA",
    "Unicode": "",
    "Currency": "MDL",
    "Capital": "Chisinau",
    "Continent": "EU",
    "DialLength": 8
  },
  {
    "Name": "Monaco",
    "DialCode": "+377",
    "Iso2": "MC",
    "EnglishName": "Monaco",
    "Iso3": "MCO",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Monaco",
    "Continent": "EU",
    "DialLength": -1
  },
  {
    "Name": "Монгол улс",
    "DialCode": "+976",
    "Iso2": "MN",
    "EnglishName": "Mongolia",
    "Iso3": "MNG",
    "Unicode": "",
    "Currency": "MNT",
    "Capital": "Ulan Bator",
    "Continent": "AS",
    "DialLength": 8
  },
  {
    "Name": "Црна Гора",
    "DialCode": "+382",
    "Iso2": "ME",
    "EnglishName": "Montenegro",
    "Iso3": "MNE",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Podgorica",
    "Continent": "EU",
    "DialLength": 8
  },
  {
    "Name": "Montserrat",
    "DialCode": "+1664",
    "Iso2": "MS",
    "EnglishName": "Montserrat",
    "Iso3": "MSR",
    "Unicode": "",
    "Currency": "XCD",
    "Capital": "Plymouth",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "المغرب",
    "DialCode": "+212",
    "Iso2": "MA",
    "EnglishName": "Morocco",
    "Iso3": "MAR",
    "Unicode": "",
    "Currency": "MAD",
    "Capital": "Rabat",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Moçambique",
    "DialCode": "+258",
    "Iso2": "MZ",
    "EnglishName": "Mozambique",
    "Iso3": "MOZ",
    "Unicode": "",
    "Currency": "MZN",
    "Capital": "Maputo",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Myanma",
    "DialCode": "+95",
    "Iso2": "MM",
    "EnglishName": "Myanmar",
    "Iso3": "MMR",
    "Unicode": "",
    "Currency": "MMK",
    "Capital": "Nay Pyi Taw",
    "Continent": "AS",
    "DialLength": [8,9,10]
  },
  {
    "Name": "Namibia",
    "DialCode": "+264",
    "Iso2": "NA",
    "EnglishName": "Namibia",
    "Iso3": "NAM",
    "Unicode": "",
    "Currency": "NAD",
    "Capital": "Windhoek",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Nauru",
    "DialCode": "+674",
    "Iso2": "NR",
    "EnglishName": "Nauru",
    "Iso3": "NRU",
    "Unicode": "",
    "Currency": "AUD",
    "Capital": "Yaren",
    "Continent": "OC",
    "DialLength": -1
  },
  {
    "Name": "नपल",
    "DialCode": "+977",
    "Iso2": "NP",
    "EnglishName": "Nepal",
    "Iso3": "NPL",
    "Unicode": "",
    "Currency": "NPR",
    "Capital": "Kathmandu",
    "Continent": "AS",
    "DialLength": 10
  },
  {
    "Name": "Nederland",
    "DialCode": "+31",
    "Iso2": "NL",
    "EnglishName": "Netherlands",
    "Iso3": "NLD",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Amsterdam",
    "Continent": "EU",
    "DialLength": 9
  },

  {
    "Name": "Nouvelle-Calédonie",
    "DialCode": "+687",
    "Iso2": "NC",
    "EnglishName": "New Caledonia",
    "Iso3": "NCL",
    "Unicode": "",
    "Currency": "XPF",
    "Capital": "Noumea",
    "Continent": "OC",
    "DialLength": 6
  },
  {
    "Name": "New Zealand",
    "DialCode": "+64",
    "Iso2": "NZ",
    "EnglishName": "New Zealand",
    "Iso3": "NZL",
    "Unicode": "",
    "Currency": "NZD",
    "Capital": "Wellington",
    "Continent": "OC",
    "DialLength": [-1,8,9,10]
  },
  {
    "Name": "Nicaragua",
    "DialCode": "+505",
    "Iso2": "NI",
    "EnglishName": "Nicaragua",
    "Iso3": "NIC",
    "Unicode": "",
    "Currency": "NIO",
    "Capital": "Managua",
    "Continent": "NA",
    "DialLength": 8
  },
  {
    "Name": "Niger",
    "DialCode": "+227",
    "Iso2": "NE",
    "EnglishName": "Niger",
    "Iso3": "NER",
    "Unicode": "",
    "Currency": "XOF",
    "Capital": "Niamey",
    "Continent": "AF",
    "DialLength": 8
  },
  {
    "Name": "Nigeria",
    "DialCode": "+234",
    "Iso2": "NG",
    "EnglishName": "Nigeria",
    "Iso3": "NGA",
    "Unicode": "",
    "Currency": "NGN",
    "Capital": "Abuja",
    "Continent": "AF",
    "DialLength": 8
  },
  {
    "Name": "Niuē",
    "DialCode": "+683",
    "Iso2": "NU",
    "EnglishName": "Niue",
    "Iso3": "NIU",
    "Unicode": "",
    "Currency": "NZD",
    "Capital": "Alofi",
    "Continent": "OC",
    "DialLength": 4
  },
  {
    "Name": "Norfolk Island",
    "DialCode": "+672",
    "Iso2": "NF",
    "EnglishName": "Norfolk Island",
    "Iso3": "NFK",
    "Unicode": "",
    "Currency": "AUD",
    "Capital": "Kingston",
    "Continent": "OC",
    "DialLength": 6
  },
  {
    "Name": "Northern Mariana Islands",
    "DialCode": "+1670",
    "Iso2": "MP",
    "EnglishName": "Northern Mariana Islands",
    "Iso3": "MNP",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "Saipan",
    "Continent": "OC",
    "DialLength": 10
  },
  {
    "Name": "Norge",
    "DialCode": "+47",
    "Iso2": "NO",
    "EnglishName": "Norway",
    "Iso3": "NOR",
    "Unicode": "",
    "Currency": "NOK",
    "Capital": "Oslo",
    "Continent": "EU",
    "DialLength": 8

  },
  {
    "Name": "عمان",
    "DialCode": "+968",
    "Iso2": "OM",
    "EnglishName": "Oman",
    "Iso3": "OMN",
    "Unicode": "",
    "Currency": "OMR",
    "Capital": "Muscat",
    "Continent": "AS",
    "DialLength": [-1,8]
  },
  {
    "Name": "Pakistan",
    "DialCode": "+92",
    "Iso2": "PK",
    "EnglishName": "Pakistan",
    "Iso3": "PAK",
    "Unicode": "",
    "Currency": "PKR",
    "Capital": "Islamabad",
    "Continent": "AS",
    "DialLength": 10
  },
  {
    "Name": "Palau",
    "DialCode": "+680",
    "Iso2": "PW",
    "EnglishName": "Palau",
    "Iso3": "PLW",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "Melekeok",
    "Continent": "OC",
    "DialLength": 7
  },
  {
    "Name": "فلسطين",
    "DialCode": "+970",
    "Iso2": "PS",
    "EnglishName": "Palestinian Territory",
    "Iso3": "PSE",
    "Unicode": "",
    "Currency": "ILS",
    "Capital": "East Jerusalem",
    "Continent": "AS",
    "DialLength": 9
  },
  {
    "Name": "Panamá",
    "DialCode": "+507",
    "Iso2": "PA",
    "EnglishName": "Panama",
    "Iso3": "PAN",
    "Unicode": "",
    "Currency": "PAB",
    "Capital": "Panama City",
    "Continent": "NA",
    "DialLength": 8
  },
  {
    "Name": "Papua Niugini",
    "DialCode": "+675",
    "Iso2": "PG",
    "EnglishName": "Papua New Guinea",
    "Iso3": "PNG",
    "Unicode": "",
    "Currency": "PGK",
    "Capital": "Port Moresby",
    "Continent": "OC",
    "DialLength": -1
  },
  {
    "Name": "Paraguay",
    "DialCode": "+595",
    "Iso2": "PY",
    "EnglishName": "Paraguay",
    "Iso3": "PRY",
    "Unicode": "",
    "Currency": "PYG",
    "Capital": "Asuncion",
    "Continent": "SA",
    "DialLength": 9
  },
  {
    "Name": "Perú",
    "DialCode": "+51",
    "Iso2": "PE",
    "EnglishName": "Peru",
    "Iso3": "PER",
    "Unicode": "",
    "Currency": "PEN",
    "Capital": "Lima",
    "Continent": "SA",
    "DialLength": 9
  },
  {
    "Name": "Pilipinas",
    "DialCode": "+63",
    "Iso2": "PH",
    "EnglishName": "Philippines",
    "Iso3": "PHL",
    "Unicode": "",
    "Currency": "PHP",
    "Capital": "Manila",
    "Continent": "AS",
    "DialLength": 10
  },
  {
    "Name": "Polska",
    "DialCode": "+48",
    "Iso2": "PL",
    "EnglishName": "Poland",
    "Iso3": "POL",
    "Unicode": "",
    "Currency": "PLN",
    "Capital": "Warsaw",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "Portugal",
    "DialCode": "+351",
    "Iso2": "PT",
    "EnglishName": "Portugal",
    "Iso3": "PRT",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Lisbon",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "Puerto Rico",
    "DialCode": "+1939",
    "Iso2": "PR",
    "EnglishName": "Puerto Rico",
    "Iso3": "PRI",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "San Juan",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "Puerto Rico",
    "DialCode": "+1787",
    "Iso2": "PR",
    "EnglishName": "Puerto Rico",
    "Iso3": "PRI",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "San Juan",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "قطر",
    "DialCode": "+974",
    "Iso2": "QA",
    "EnglishName": "Qatar",
    "Iso3": "QAT",
    "Unicode": "",
    "Currency": "QAR",
    "Capital": "Doha",
    "Continent": "AS",
    "DialLength": 8
  },
  {
    "Name": "România",
    "DialCode": "+40",
    "Iso2": "RO",
    "EnglishName": "Romania",
    "Iso3": "ROU",
    "Unicode": "",
    "Currency": "RON",
    "Capital": "Bucharest",
    "Continent": "EU",
    "DialLength": 10
  },
  {
    "Name": "Россия",
    "DialCode": "+7",
    "Iso2": "RU",
    "EnglishName": "Russia",
    "Iso3": "RUS",
    "Unicode": "",
    "Currency": "RUB",
    "Capital": "Moscow",
    "Continent": "EU",
    "DialLength": 10
  },
  {
    "Name": "Rwanda",
    "DialCode": "+250",
    "Iso2": "RW",
    "EnglishName": "Rwanda",
    "Iso3": "RWA",
    "Unicode": "",
    "Currency": "RWF",
    "Capital": "Kigali",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "La Réunion",
    "DialCode": "+262",
    "Iso2": "RE",
    "EnglishName": "Reunion",
    "Iso3": "REU",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Saint-Denis",
    "Continent": "AF",
    "DialLength": [-1,9,12]
  },
  {
    "Name": "Saint-Barthélemy",
    "DialCode": "+590",
    "Iso2": "BL",
    "EnglishName": "Saint Barthelemy",
    "Iso3": "BLM",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Gustavia",
    "Continent": "NA",
    "DialLength": -1
  },
  {
    "Name": "Saint Helena",
    "DialCode": "+290",
    "Iso2": "SH",
    "EnglishName": "Saint Helena",
    "Iso3": "SHN",
    "Unicode": "",
    "Currency": "SHP",
    "Capital": "Jamestown",
    "Continent": "AF",
    "DialLength": 4
  },
  {
    "Name": "Saint Kitts and Nevis",
    "DialCode": "+1869",
    "Iso2": "KN",
    "EnglishName": "Saint Kitts and Nevis",
    "Iso3": "KNA",
    "Unicode": "",
    "Currency": "XCD",
    "Capital": "Basseterre",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "Saint Lucia",
    "DialCode": "+1758",
    "Iso2": "LC",
    "EnglishName": "Saint Lucia",
    "Iso3": "LCA",
    "Unicode": "",
    "Dial": "+1-758",
    "Currency": "XCD",
    "Capital": "Castries",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "Saint-Martin",
    "DialCode": "+590",
    "Iso2": "MF",
    "EnglishName": "Saint Martin",
    "Iso3": "MAF",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Marigot",
    "Continent": "NA",
    "DialLength": -1
  },
  {
    "Name": "Saint-Pierre-et-Miquelon",
    "DialCode": "+508",
    "Iso2": "PM",
    "EnglishName": "Saint Pierre and Miquelon",
    "Iso3": "SPM",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Saint-Pierre",
    "Continent": "NA",
    "DialLength": -1
  },
  {
    "Name": "Saint Vincent and the Grenadines",
    "DialCode": "+1784",
    "Iso2": "VC",
    "EnglishName": "Saint Vincent and the Grenadines",
    "Iso3": "VCT",
    "Unicode": "",
    "Currency": "XCD",
    "Capital": "Kingstown",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "Samoa",
    "DialCode": "+685",
    "Iso2": "WS",
    "EnglishName": "Samoa",
    "Iso3": "WSM",
    "Unicode": "",
    "Currency": "WST",
    "Capital": "Apia",
    "Continent": "OC",
    "DialLength": 5
  },
  {
    "Name": "San Marino",
    "DialCode": "+378",
    "Iso2": "SM",
    "EnglishName": "San Marino",
    "Iso3": "SMR",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "San Marino",
    "Continent": "EU",
    "DialLength": -1
  },
  {
    "Name": "São Tomé e Príncipe",
    "DialCode": "+239",
    "Iso2": "ST",
    "EnglishName": "Sao Tome and Principe",
    "Iso3": "STP",
    "Unicode": "",
    "Currency": "STD",
    "Capital": "Sao Tome",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "العربية السعودية",
    "DialCode": "+966",
    "Iso2": "SA",
    "EnglishName": "Saudi Arabia",
    "Iso3": "SAU",
    "Unicode": "",
    "Currency": "SAR",
    "Capital": "Riyadh",
    "Continent": "AS",
    "DialLength": 9
  },
  {
    "Name": "Sénégal",
    "DialCode": "+221",
    "Iso2": "SN",
    "EnglishName": "Senegal",
    "Iso3": "SEN",
    "Unicode": "",
    "Currency": "XOF",
    "Capital": "Dakar",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Србија",
    "DialCode": "+381",
    "Iso2": "RS",
    "EnglishName": "Serbia",
    "Iso3": "SRB",
    "Unicode": "",
    "Currency": "RSD",
    "Capital": "Belgrade",
    "Continent": "EU",
    "DialLength": [8,9]
  },
  {
    "Name": "Seychelles",
    "DialCode": "+248",
    "Iso2": "SC",
    "EnglishName": "Seychelles",
    "Iso3": "SYC",
    "Unicode": "",
    "Currency": "SCR",
    "Capital": "Victoria",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Sierra Leone",
    "DialCode": "+232",
    "Iso2": "SL",
    "EnglishName": "Sierra Leone",
    "Iso3": "SLE",
    "Unicode": "",
    "Currency": "SLL",
    "Capital": "Freetown",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Singapore",
    "DialCode": "+65",
    "Iso2": "SG",
    "EnglishName": "Singapore",
    "Iso3": "SGP",
    "Unicode": "",
    "Currency": "SGD",
    "Capital": "Singapur",
    "Continent": "AS",
    "DialLength": 8
  },
  {
    "Name": "Slovensko",
    "DialCode": "+421",
    "Iso2": "SK",
    "EnglishName": "Slovakia",
    "Iso3": "SVK",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Bratislava",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "Slovenija",
    "DialCode": "+386",
    "Iso2": "SI",
    "EnglishName": "Slovenia",
    "Iso3": "SVN",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Ljubljana",
    "Continent": "EU",
    "DialLength": -1
  },
  {
    "Name": "Solomon Islands",
    "DialCode": "+677",
    "Iso2": "SB",
    "EnglishName": "Solomon Islands",
    "Iso3": "SLB",
    "Unicode": "",
    "Currency": "SBD",
    "Capital": "Honiara",
    "Continent": "OC",
    "DialLength": 7
  },
  {
    "Name": "Soomaaliya",
    "DialCode": "+252",
    "Iso2": "SO",
    "EnglishName": "Somalia",
    "Iso3": "SOM",
    "Unicode": "",
    "Currency": "SOS",
    "Capital": "Mogadishu",
    "Continent": "AF",
    "DialLength": [7,8]
  },
  {
    "Name": "South Africa",
    "DialCode": "+27",
    "Iso2": "ZA",
    "EnglishName": "South Africa",
    "Iso3": "ZAF",
    "Unicode": "",
    "Currency": "ZAR",
    "Capital": "Pretoria",
    "Continent": "AF",
    "DialLength": 9
  },
  {
    "Name": "South Sudan",
    "DialCode": "+211",
    "Iso2": "SS",
    "EnglishName": "South Sudan",
    "Iso3": "SSD",
    "Unicode": "",
    "Dial": "211",
    "Currency": "SSP",
    "Capital": "Juba",
    "Continent": "AF"
  },
  {
    "Name": "South Georgia",
    "DialCode": "+500",
    "Iso2": "GS",
    "EnglishName": "South Georgia and the South Sandwich Islands",
    "Iso3": "SGS",
    "Unicode": "",
    "Currency": "GBP",
    "Capital": "Grytviken",
    "Continent": "AN",
    "DialLength": -1
  },
  {
    "Name": "España",
    "DialCode": "+34",
    "Iso2": "ES",
    "EnglishName": "Spain",
    "Iso3": "ESP",
    "Unicode": "",
    "Currency": "EUR",
    "Capital": "Madrid",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "Sri Lanka",
    "DialCode": "+94",
    "Iso2": "LK",
    "EnglishName": "Sri Lanka",
    "Iso3": "LKA",
    "Unicode": "",
    "Currency": "LKR",
    "Capital": "Colombo",
    "Continent": "AS",
    "DialLength": 7
  },
  {
    "Name": "السودان",
    "DialCode": "+249",
    "Iso2": "SD",
    "EnglishName": "Sudan",
    "Iso3": "SDN",
    "Unicode": "",
    "Currency": "SDG",
    "Capital": "Khartoum",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Suriname",
    "DialCode": "+597",
    "Iso2": "SR",
    "EnglishName": "Suriname",
    "Iso3": "SUR",
    "Unicode": "",
    "Currency": "SRD",
    "Capital": "Paramaribo",
    "Continent": "SA",
    "DialLength": -1
  },
  {
    "Name": "Svalbard og Jan Mayen",
    "DialCode": "+47",
    "Iso2": "SJ",
    "EnglishName": "Svalbard and Jan Mayen",
    "Iso3": "SJM",
    "Unicode": "",
    "Currency": "NOK",
    "Capital": "Longyearbyen",
    "Continent": "EU",
    "DialLength": -1
  },
  {
    "Name": "Swaziland",
    "DialCode": "+268",
    "Iso2": "SZ",
    "EnglishName": "Swaziland",
    "Iso3": "SWZ",
    "Unicode": "",
    "Currency": "SZL",
    "Capital": "Mbabane",
    "Continent": "AF",
    "DialLength":[]
  },
  {
    "Name": "Sverige",
    "DialCode": "+46",
    "Iso2": "SE",
    "EnglishName": "Sweden",
    "Iso3": "SWE",
    "Unicode": "",
    "Currency": "SEK",
    "Capital": "Stockholm",
    "Continent": "EU",
    "DialLength": [-1,7,10]
  },
  {
    "Name": "Schweiz",
    "DialCode": "+41",
    "Iso2": "CH",
    "EnglishName": "Switzerland",
    "Iso3": "CHE",
    "Unicode": "",
    "Currency": "CHF",
    "Capital": "Berne",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "سوريا",
    "DialCode": "+963",
    "Iso2": "SY",
    "EnglishName": "Syria",
    "Iso3": "SYR",
    "Unicode": "",
    "Currency": "SYP",
    "Capital": "Damascus",
    "Continent": "AS",
    "DialLength": 9
  },
  {
    "Name": "臺灣",
    "DialCode": "+886",
    "Iso2": "TW",
    "EnglishName": "Taiwan",
    "Iso3": "TWN",
    "Unicode": "",
    "Currency": "TWD",
    "Capital": "Taipei",
    "Continent": "AS",
    "DialLength": 9
  },
  {
    "Name": "Тоҷикистон",
    "DialCode": "+992",
    "Iso2": "TJ",
    "EnglishName": "Tajikistan",
    "Iso3": "TJK",
    "Unicode": "",
    "Currency": "TJS",
    "Capital": "Dushanbe",
    "Continent": "AS",
    "DialLength": -1
  },
  {
    "Name": "Tanzania",
    "DialCode": "+255",
    "Iso2": "CI",
    "EnglishName": "Ivory Coast",
    "Iso3": "CIV",
    "Unicode": "",
    "Currency": "XOF",
    "Capital": "Yamoussoukro",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "ประเทศไทย",
    "DialCode": "+66",
    "Iso2": "TH",
    "EnglishName": "Thailand",
    "Iso3": "THA",
    "Unicode": "",
    "Currency": "THB",
    "Capital": "Bangkok",
    "Continent": "AS",
    "DialLength": 9
  },
  {
    "Name": "Timor-Leste",
    "DialCode": "+670",
    "Iso2": "TL",
    "EnglishName": "East Timor",
    "Iso3": "TLS",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "Dili",
    "Continent": "OC",
    "DialLength": 8
  },
  {
    "Name": "Togo",
    "DialCode": "+228",
    "Iso2": "TG",
    "EnglishName": "Togo",
    "Iso3": "TGO",
    "Unicode": "",
    "Currency": "XOF",
    "Capital": "Lome",
    "Continent": "AF",
    "DialLength": 8
  },
  {
    "Name": "Tokelau",
    "DialCode": "+690",
    "Iso2": "TK",
    "EnglishName": "Tokelau",
    "Iso3": "TKL",
    "Unicode": "",
    "Currency": "NZD",
    "Capital": "",
    "Continent": "OC",
    "DialLength": -1
  },
  {
    "Name": "Tonga",
    "DialCode": "+676",
    "Iso2": "TO",
    "EnglishName": "Tonga",
    "Iso3": "TON",
    "Unicode": "",
    "Currency": "TOP",
    "Capital": "Nuku'alofa",
    "Continent": "OC",
    "DialLength": -1
  },
  {
    "Name": "Trinidad and Tobago",
    "DialCode": "+1868",
    "Iso2": "TT",
    "EnglishName": "Trinidad and Tobago",
    "Iso3": "TTO",
    "Unicode": "",
    "Currency": "TTD",
    "Capital": "Port of Spain",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "تونس",
    "DialCode": "+216",
    "Iso2": "TN",
    "EnglishName": "Tunisia",
    "Iso3": "TUN",
    "Unicode": "",
    "Currency": "TND",
    "Capital": "Tunis",
    "Continent": "AF",
    "DialLength": 8
  },
  {
    "Name": "Türkiye",
    "DialCode": "+90",
    "Iso2": "TR",
    "EnglishName": "Turkey",
    "Iso3": "TUR",
    "Unicode": "",
    "Currency": "TRY",
    "Capital": "Ankara",
    "Continent": "AS",
    "DialLength": 11
  },
  {
    "Name": "Türkmenistan",
    "DialCode": "+993",
    "Iso2": "TM",
    "EnglishName": "Turkmenistan",
    "Iso3": "TKM",
    "Unicode": "",
    "Currency": "TMT",
    "Capital": "Ashgabat",
    "Continent": "AS",
    "DialLength": -1
  },
  {
    "Name": "Turks and Caicos Islands",
    "DialCode": "+1649",
    "Iso2": "TC",
    "EnglishName": "Turks and Caicos Islands",
    "Iso3": "TCA",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "Cockburn Town",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "Tuvalu",
    "DialCode": "+688",
    "Iso2": "TV",
    "EnglishName": "Tuvalu",
    "Iso3": "TUV",
    "Unicode": "",
    "Currency": "AUD",
    "Capital": "Funafuti",
    "Continent": "OC",
    "DialLength": -1
  },
  {
    "Name": "Uganda",
    "DialCode": "+256",
    "Iso2": "UG",
    "EnglishName": "Uganda",
    "Iso3": "UGA",
    "Unicode": "",
    "Currency": "UGX",
    "Capital": "Kampala",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Україна",
    "DialCode": "+380",
    "Iso2": "UA",
    "EnglishName": "Ukraine",
    "Iso3": "UKR",
    "Unicode": "",
    "Currency": "UAH",
    "Capital": "Kiev",
    "Continent": "EU",
    "DialLength": 9
  },
  {
    "Name": "دولة الإمارات العربية المتحدة",
    "DialCode": "+971",
    "Iso2": "AE",
    "EnglishName": "United Arab Emirates",
    "Iso3": "ARE",
    "Unicode": "",
    "Currency": "AED",
    "Capital": "Abu Dhabi",
    "Continent": "AS",
    "DialLength": 9
  },
  {
    "Name": "United Kingdom",
    "DialCode": "+44",
    "Iso2": "GB",
    "EnglishName": "United Kingdom",
    "Iso3": "GBR",
    "Unicode": "",
    "Currency": "GBP",
    "Capital": "London",
    "Continent": "EU",
    "DialLength": 10
  },
  {
    "Name": "United States",
    "DialCode": "+1",
    "Iso2": "US",
    "EnglishName": "United States",
    "Iso3": "USA",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "Washington",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "Uruguay",
    "DialCode": "+598",
    "Iso2": "UY",
    "EnglishName": "Uruguay",
    "Iso3": "URY",
    "Unicode": "",
    "Currency": "UYU",
    "Capital": "Montevideo",
    "Continent": "SA",
    "DialLength": -1
  },
  {
    "Name": "O‘zbekiston",
    "DialCode": "+998",
    "Iso2": "UZ",
    "EnglishName": "Uzbekistan",
    "Iso3": "UZB",
    "Unicode": "",
    "Currency": "UZS",
    "Capital": "Tashkent",
    "Continent": "AS",
    "DialLength": -1
  },
  {
    "Name": "Vanuatu",
    "DialCode": "+678",
    "Iso2": "VU",
    "EnglishName": "Vanuatu",
    "Iso3": "VUT",
    "Unicode": "",
    "Currency": "VUV",
    "Capital": "Port Vila",
    "Continent": "OC",
    "DialLength": -1
  },
  {
    "Name": "Venezuela",
    "DialCode": "+58",
    "Iso2": "VE",
    "EnglishName": "Venezuela",
    "Iso3": "VEN",
    "Unicode": "",
    "Currency": "VEF",
    "Capital": "Caracas",
    "Continent": "SA",
    "DialLength": 7
  },
  {
    "Name": "Việt Nam",
    "DialCode": "+84",
    "Iso2": "VN",
    "EnglishName": "Vietnam",
    "Iso3": "VNM",
    "Unicode": "",
    "Currency": "VND",
    "Capital": "Hanoi",
    "Continent": "AS",
    "DialLength": 9
  },
  {
    "Name": "British Virgin Islands",
    "DialCode": "+1284",
    "Iso2": "VG",
    "EnglishName": "British Virgin Islands",
    "Iso3": "VGB",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "Road Town",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "United States Virgin Islands",
    "DialCode": "+1340",
    "Iso2": "VI",
    "EnglishName": "U.S. Virgin Islands",
    "Iso3": "VIR",
    "Unicode": "",
    "Currency": "USD",
    "Capital": "Charlotte Amalie",
    "Continent": "NA",
    "DialLength": 10
  },
  {
    "Name": "Wallis et Futuna",
    "DialCode": "+681",
    "Iso2": "WF",
    "EnglishName": "Wallis and Futuna",
    "Iso3": "WLF",
    "Unicode": "",
    "Currency": "XPF",
    "Capital": "Mata Utu",
    "Continent": "OC",
    "DialLength": -1
  },
  {
    "Name": "اليَمَن",
    "DialCode": "+967",
    "Iso2": "YE",
    "EnglishName": "Yemen",
    "Iso3": "YEM",
    "Unicode": "",
    "Currency": "YER",
    "Capital": "Sanaa",
    "Continent": "AS",
    "DialLength": 9
  },
  {
    "Name": "Zambia",
    "DialCode": "+260",
    "Iso2": "ZM",
    "EnglishName": "Zambia",
    "Iso3": "ZMB",
    "Unicode": "",
    "Currency": "ZMK",
    "Capital": "Lusaka",
    "Continent": "AF",
    "DialLength": -1
  },
  {
    "Name": "Zimbabwe",
    "DialCode": "+263",
    "Iso2": "ZW",
    "EnglishName": "Zimbabwe",
    "Iso3": "ZWE",
    "Unicode": "",
    "Currency": "ZWL",
    "Capital": "Harare",
    "Continent": "AF",
    "DialLength": -1

  }
]''';

/*{
    "name": "Territoire des Terres australes et antarctiques fr",
    "code": "TF",
    "dial_code": "+262"
  },
  {
    "name": "Netherlands Antilles",
    "code": "AN",
    "dial_code": "+599"
  },
  {
    "name": "Pitcairn Islands",
    "code": "PN",
    "dial_code": "+64"

  },*/