name: super_strapi
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0-133.7.beta'

dependencies:
#  path: ^1.7.0
  args: ^1.6.0
  path: ^1.7.0
  code_builder: ^3.6.0
  dart_style: ^1.3.12
  inflection2: ^0.4.3


  simple_strapi:
    path: ./simple_strapi


dev_dependencies:
  pedantic: ^1.9.0
