name: super_strapi
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '2.13.0-116.0.dev'

dependencies:
#  path: ^1.7.0
  args: ^2.0.0
  path: ^1.7.0
  code_builder: ^3.7.0
  dart_style: any
  inflection2: ^0.4.3
  yaml: ^3.1.0





dev_dependencies:
  pedantic: ^1.9.0
